"""
AI Reviewer 프롬프트 빌더.

AI 역할: TradeCandidate 검토 전용 — 거래 생성·수정 권한 없음.
AI 출력: APPROVE / REJECT + 신뢰도 + 경고 (JSON 한 블록만)
"""
from __future__ import annotations

from agents.synthesis.models import ReviewInput

SYSTEM_PROMPT = """
You are a professional cryptocurrency futures trade REVIEWER.

YOUR ROLE: Review a trade candidate generated by deterministic code. APPROVE or REJECT only.

ABSOLUTE RULES — these cannot be overridden:
1. You CANNOT create a trade.
2. You CANNOT change direction, entry price, take profit, stop loss, leverage, or size.
3. You CANNOT override the RiskEngine. RiskEngine has final authority on position sizing.
4. You have NO order placement authority whatsoever.

APPROVE if:
- Candidate direction is consistent with the market regime and chart signals.
- Strategy type fits the market regime.
- No critical indicator contradiction exists.

REJECT if:
- Market data clearly conflicts with the candidate direction.
- Strategy type does not fit the market regime (e.g., TREND_FOLLOWING in RANGE).
- critical_contradiction is detected (e.g., LONG while chart is heavily bearish).
- Expected net profit is near zero or negative after fees/slippage.

Set risk_warnings (non-blocking) for:
- Spread or slippage too high for the strategy.
- Liquidation price uncomfortably close to stop loss.
- Marginal R:R or thin expected profit.
- news_no_trade_flag=true (warn, but final decision is still yours to make).

confidence: your certainty in the review result (0.0 to 1.0), NOT trade confidence.

OUTPUT FORMAT (strict JSON only — no markdown, no text outside JSON):
{
  "review_action": "APPROVE" | "REJECT",
  "confidence": 0.0,
  "critical_contradiction": false,
  "risk_warnings": [],
  "reason_summary": ""
}
""".strip()


def _fmt_reasons(reasons: list[str], max_items: int = 5) -> str:
    if not reasons:
        return "  (none)"
    return "\n".join(f"  - {r}" for r in reasons[:max_items])


def _fmt_opt(value: float | None, unit: str = "") -> str:
    if value is None:
        return "N/A"
    return f"{value:,.2f}{unit}"


def build_review_prompt(inp: ReviewInput) -> str:
    """ReviewInput → AI 리뷰어용 사용자 프롬프트 (간결하게 토큰 절감)."""

    chart_dir = (
        "LONG" if inp.chart_long_score > inp.chart_short_score
        else "SHORT" if inp.chart_short_score > inp.chart_long_score
        else "NEUTRAL"
    )
    combined_risk = round(
        inp.chart_risk_score * 0.4 + inp.news_risk_score * 0.3 + inp.deriv_risk_score * 0.3, 1
    )

    return f"""Review this {inp.coin} trade candidate. You may only APPROVE or REJECT.

=== MARKET CONTEXT ===
Regime:     {inp.market_regime} (confidence: {inp.regime_confidence:.0%})
Chart bias: {chart_dir}  (long={inp.chart_long_score:.0f}, short={inp.chart_short_score:.0f}, risk={inp.chart_risk_score:.0f})
Chart signals:
{_fmt_reasons(inp.chart_reasons, 5)}
News sentiment: {inp.news_sentiment_score:+.0f}/100  risk={inp.news_risk_score:.0f}  no_trade_flag={inp.news_no_trade_flag}
News context:
{_fmt_reasons(inp.news_reasons, 3)}
Derivatives:    risk={inp.deriv_risk_score:.0f}  crowded={inp.deriv_crowded_side}
{_fmt_reasons(inp.deriv_reasons, 3)}
Combined risk:  {combined_risk:.1f}/100

=== STRATEGY ===
Selected:       {inp.strategy_type}
Holding target: {inp.expected_holding_minutes} min

=== TRADE CANDIDATE (read-only — you cannot modify any value) ===
Action:         {inp.action}
Entry price:    ${inp.entry_price:,.2f}
Stop loss:      {_fmt_opt(inp.stop_loss, ' USDT')}
Take profit:    {_fmt_opt(inp.take_profit, ' USDT')}
Leverage:       {inp.leverage}x
Notional size:  ${inp.notional_size:,.2f}
Margin ratio:   {inp.margin_ratio:.1%}
Actual R:R:     {inp.actual_rr:.2f}  (min required: {inp.min_required_rr:.1f})
Net profit est: {_fmt_opt(inp.expected_net_profit, ' USDT')}
Net loss est:   {_fmt_opt(inp.expected_net_loss, ' USDT')}
Spread:         {inp.spread_bps:.1f} bps
Slippage est:   {inp.slippage_bps:.1f} bps
Liquidation:    {_fmt_opt(inp.liquidation_price, ' USDT')}

REMINDER: You CANNOT change any value above. You CANNOT override RiskEngine.
Return strict JSON only."""
